name: CI Check

on:
    pull_request:
      paths:
        - 'frontApi/**'
      branches:
        - '*'

jobs:
    run-test:
        runs-on: ubuntu-latest
        steps:
        - name: Clone
          uses: actions/checkout@v4

        - name: Setup Java
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'

        - name: Build Project
          working-directory: ./frontapi
          run: ./gradlew build

        - name: Run Tests
          working-directory: ./frontapi
          run: ./gradlew test